# Generated by Django 5.0.6 on 2024-05-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='subcategoryimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
